pipeline {
    agent any

    stages {
		stage ('Build artifacts') {
			parallel {
			
				//Publish the artifacts to a folder, will reuse these so we're not rebuilding the artifacts at every stage
				stage('Build app') {
					steps {
						retry(3) {
							sh 'dotnet publish ./ForLoops/ForLoops.csproj -c Release -r win10-x64 -o /tmp/app'
						}
					}
				}

				//Publish the artifacts to a folder, will reuse these so we're not rebuilding the artifacts at every stage
				stage('Build tests') {
					steps {
						retry(3) {
							sh 'dotnet publish ./ForLoopsTest/ForLoopsTest.csproj -c Release -r win10-x64 -o /tmp/tests'
						}
					}
				}
			}
		}
        stage('Test') {
		//Run the tests using the artifacts we built earlier. Notice the --no-build option
				stage('Unit test') {
					steps {
						sh 'dotnet test ./ForLoopsTest/ForLoopsTest.csproj -c Release -r win10-x64 -o /tmp/tests' 
				}
        }
       
        }
    }
}